format = "$all"
add_newline = false
command_timeout = 2000
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[♥](bold green)"
error_symbol = "[♡](bold red)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
read_only = " "

[line_break]
disabled = true

[git_branch]
disabled = false
format = "[$symbol$branch]( $style ) "
style = "bold yellow"
symbol = " "

[git_commit]
tag_symbol = '  '

[aws]
disabled = true

[buf]
disabled = true

[c]
commands = [['clang', '--version'], ['cc', '--version'], ['gcc', '--version']]
symbol = " "

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[dart]
symbol = " "

[docker_context]
symbol = " "

[dotnet]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = " "

[fennel]
disabled = true

[fossil_branch]
symbol = " "

[gcloud]
disabled = true

[golang]
symbol = " "

[guix_shell]
disabled = true

[gradle]
disabled = true

[haskell]
symbol = " "

[haxe]
disabled = true

[hg_branch]
symbol = " "

[java]
disabled = true

[julia]
symbol = " "

[kotlin]
disabled = true

[kubernetes]
disabled = true

[lua]
symbol = " "

[nim]
disabled = true

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[opa]
disabled = true

[openstack]
disabled = true

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
openSUSE = " "
OracleLinux = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[python]
symbol = " "

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[rust]
symbol = " "

[scala]
symbol = " "

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[swift]
symbol = " "

[terraform]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true